<?php
    $lang['number']   = 'Referensi';
    $lang['date']     = 'Tanggal Penagihan';
    $lang['time']     = 'Waktu Penagihan';
    $lang['due']      = 'Jatuh tempo';
    $lang['to']       = 'Tagihan kepada';
    $lang['from']     = 'Tagihan dari';
    $lang['product']  = 'Produk';
    $lang['qty']      = 'Jumlah';
    $lang['price']    = 'Harga';
    $lang['discount'] = 'Diskon';
    $lang['vat']      = 'PPN';
    $lang['total']    = 'Total';
    $lang['page']     = 'Halaman';
    $lang['page_of']  = 'dari';
